# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/Lightly/kdecoration/config/ui/oceandetectwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OceanDetectWidget(object):
    def setupUi(self, OceanDetectWidget):
        OceanDetectWidget.setObjectName("OceanDetectWidget")
        OceanDetectWidget.resize(400, 239)
        self.verticalLayout = QtWidgets.QVBoxLayout(OceanDetectWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(OceanDetectWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.windowClass = QtWidgets.QLabel(self.groupBox)
        self.windowClass.setText("TextLabel")
        self.windowClass.setObjectName("windowClass")
        self.gridLayout.addWidget(self.windowClass, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.windowTitle = QtWidgets.QLabel(self.groupBox)
        self.windowTitle.setText("TextLabel")
        self.windowTitle.setObjectName("windowTitle")
        self.gridLayout.addWidget(self.windowTitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(OceanDetectWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.windowClassCheckBox = QtWidgets.QRadioButton(self.groupBox_2)
        self.windowClassCheckBox.setObjectName("windowClassCheckBox")
        self.verticalLayout_2.addWidget(self.windowClassCheckBox)
        self.windowTitleCheckBox = QtWidgets.QRadioButton(self.groupBox_2)
        self.windowTitleCheckBox.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.windowTitleCheckBox.setObjectName("windowTitleCheckBox")
        self.verticalLayout_2.addWidget(self.windowTitleCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(OceanDetectWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OceanDetectWidget)
        self.buttonBox.accepted.connect(OceanDetectWidget.accept) # type: ignore
        self.buttonBox.rejected.connect(OceanDetectWidget.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OceanDetectWidget)

    def retranslateUi(self, OceanDetectWidget):
        _translate = QtCore.QCoreApplication.translate
        OceanDetectWidget.setWindowTitle(_translate("OceanDetectWidget", "Dialog"))
        self.groupBox.setTitle(_translate("OceanDetectWidget", "Information about Selected Window"))
        self.label.setText(_translate("OceanDetectWidget", "Class: "))
        self.label_2.setText(_translate("OceanDetectWidget", "Title: "))
        self.groupBox_2.setTitle(_translate("OceanDetectWidget", "Window Property Selection"))
        self.windowClassCheckBox.setText(_translate("OceanDetectWidget", "Use window class (whole application)"))
        self.windowTitleCheckBox.setText(_translate("OceanDetectWidget", "Use window title"))
